services:
  service-a:
    build: ./service-a
    container_name: lab2-service-a
    ports:
      - "5000:5000"
    depends_on:
      - service-b

  service-b:
    build: ./service-b
    container_name: lab2-service-b
    ports:
      - "5001:5001"