services:
  db:
    image: postgres:16-alpine
    container_name: lab5-postgres-db
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_password
    ports:
      - "5432:5432"
    volumes:
      - lab5_postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: lab5-backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: todo_password
      DB_PORT: 5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: lab5-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  lab5_postgres_data: